### ISSUE TITLE
Getting error after changing some code on client

### ISSUE THREAD

**Issue by beseffort** [Metnew/webpack-get-code-on-done#8]
I started my project based on suicrux boilerplate.
Below error suddenly happened while building project after changing minor code blocks on client side.

Error: webpack-get-code-on-done: Compiled code is 'undefined'. Please check latest changes that may produced this error. TypeError: Cannot read property 'createElement' of undefined

This error is not disappeared once it appeared, even though I revert code changes.
What is this error related with?

**Comment by Metnew** [comment]
Hi @beseffort 

>TL;DR: probably, you use some client-only libs, globals on the server.

At first, try to add this snippet to `webpack_config/server.js`:
```js
process.on('uncaughtException', err => {
	console.error(' UNCAUGHT EXCEPTION ')
	console.error(err.stack || err.message)
})
```

It should log the full error trace.

Your code generates an error at runtime. The object with method `createElement` is undefined (Could it be a `document`?) was evaluated by the server as `undefined`. For the server, `document` and `window` are `undefined` by default. As of it was an error, server couldn't generate a meaningful build and breaks.

Some React libs aren't SSR compatible and break the server at runtime. 

If this issue was generated by client-side globals, then you could add this snippet to your server-side code near `global.window = {}`:
```js
global.document = {
   createElement(){}
}
``` 


This crash on server-side is a known issue and it would be fixed as soon as Razzle will be integrated as a base toolkit for the suicrux. (It'd be soon, really.)

**Comment by beseffort** [comment]
Hi @Metnew 
Thanks for your reply.
I basically understood the reason of this error what you mentioned, but I'm not sure why the error doesn't occur from the first when I try building project.
As I wrote, it happened after a while I added my codes.
Furthermore, sometimes error occurs and sometimes not with even same code.
Could you explain this?
FYI, I use exactly same webpack configuration with suicrux template.

```
webpack_config/
             assets/
             client/
                     webpack.base.js
                     webpack.dev.babel.js
                     webpack.prod.babel.js
             server/
                     webpack.base.js
                     webpack.dev.babel.js
                     webpack.prod.babel.js
             config.js
             devServer.js
             webpack.isomorphic.js
```

Where do you want to add this code snippet to?
```
process.on('uncaughtException', err => {
	console.error(' UNCAUGHT EXCEPTION ')
	console.error(err.stack || err.message)
})
```

Also, same error still occurs even though I added below code to server side.
```
global.document = {
   createElement(){}
}
```

**Comment by Metnew** [comment]
Try to add this snippet to the `devServer` file in `webpack_config`
It could be an async action that works with DOM, but it's impossible in Node environment, so it crashes an app. Probably, a `setTimeout` or an async manipulation with DOM

> ~~Also, fix for this issue + razzle integration will be tomorrow~~

**Comment by beseffort** [comment]
I tried it but error stack shows same message.
```
SERVER IS LISTENING ON http://localhost:3000
AutoDllPlugin: is valid cache? true
webpack building...
 UNCAUGHT EXCEPTION
Error: webpack-get-code-on-done: Compiled code is 'undefined'. Please check latest changes that may produced this error. TypeError: Cannot read property 'createElement' of undefined
    at Compiler.compiler.plugin.stats (/Volumes/DATA/Work/React/OptionsEDU Tools/node_modules/webpack-get-code-on-done/src/index.js:81:10)
    at Compiler.applyPlugins (/Volumes/DATA/Work/React/OptionsEDU Tools/node_modules/webpack/node_modules/tapable/lib/Tapable.js:61:14)
    at Watching._done (/Volumes/DATA/Work/React/OptionsEDU Tools/node_modules/webpack/lib/Compiler.js:105:17)
    at compiler.emitRecords.err (/Volumes/DATA/Work/React/OptionsEDU Tools/node_modules/webpack/lib/Compiler.js:79:19)
    at Compiler.emitRecords (/Volumes/DATA/Work/React/OptionsEDU Tools/node_modules/webpack/lib/Compiler.js:371:38)
    at compiler.emitAssets.err (/Volumes/DATA/Work/React/OptionsEDU Tools/node_modules/webpack/lib/Compiler.js:62:20)
    at applyPluginsAsyncSeries1.err (/Volumes/DATA/Work/React/OptionsEDU Tools/node_modules/webpack/lib/Compiler.js:364:12)
    at next (/Volumes/DATA/Work/React/OptionsEDU Tools/node_modules/webpack/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/Volumes/DATA/Work/React/OptionsEDU Tools/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Volumes/DATA/Work/React/OptionsEDU Tools/node_modules/webpack/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/Volumes/DATA/Work/React/OptionsEDU Tools/node_modules/webpack/lib/Compiler.js:361:9)
    at require.forEach.err (/Volumes/DATA/Work/React/OptionsEDU Tools/node_modules/webpack/lib/Compiler.js:350:15)
    at /Volumes/DATA/Work/React/OptionsEDU Tools/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/Volumes/DATA/Work/React/OptionsEDU Tools/node_modules/async/dist/async.js:1050:13)
    at /Volumes/DATA/Work/React/OptionsEDU Tools/node_modules/async/dist/async.js:958:16
    at MemoryFileSystem.writeFile (/Volumes/DATA/Work/React/OptionsEDU Tools/node_modules/memory-fs/lib/MemoryFileSystem.js:328:9)
    at writeOut (/Volumes/DATA/Work/React/OptionsEDU Tools/node_modules/webpack/lib/Compiler.js:339:28)
    at require.forEach (/Volumes/DATA/Work/React/OptionsEDU Tools/node_modules/webpack/lib/Compiler.js:345:12)
    at /Volumes/DATA/Work/React/OptionsEDU Tools/node_modules/async/dist/async.js:3096:16
    at eachOfArrayLike (/Volumes/DATA/Work/React/OptionsEDU Tools/node_modules/async/dist/async.js:1055:9)
    at eachOf (/Volumes/DATA/Work/React/OptionsEDU Tools/node_modules/async/dist/async.js:1103:5)
    at Object.eachLimit (/Volumes/DATA/Work/React/OptionsEDU Tools/node_modules/async/dist/async.js:3158:5)
    at emitFiles (/Volumes/DATA/Work/React/OptionsEDU Tools/node_modules/webpack/lib/Compiler.js:315:21)
    at Immediate.<anonymous> (/Volumes/DATA/Work/React/OptionsEDU Tools/node_modules/memory-fs/lib/MemoryFileSystem.js:288:4)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
```

**Comment by Metnew** [comment]
do you use the object with `createElement` method somewhere in your code?

**Comment by beseffort** [comment]
There's only one code block in 'src/common/containers/App/index.jsx', which is originally there in suicrux template.
```
componentDidMount () {
		if (process.env.BROWSER && process.env.SENTRY_PUBLIC_DSN) {
			const script = document.createElement('script')
			script.type = 'text/javascript'
			script.crossorigin = 'anonymous'
			script.async = true
			script.onload = () => {
				Raven.config(process.env.SENTRY_PUBLIC_DSN).install()
			}
			script.src = 'https://cdn.ravenjs.com/3.19.1/raven.min.js'
			document.body.appendChild(script)
		}

		if (process.env.BROWSER && process.env.GA_ID) {
			ReactGA.initialize(process.env.GA_ID)
		}
}
```
May I have your skype id please, to have a quick chat.

**Comment by Metnew** [comment]
https://gitter.im/suicrux/Lobby

**Comment by Louis-P** [comment]
I am having the exact same problem. It is the first time I encountered this error after several weeks working with this template.

**Comment by Metnew** [comment]
@beseffort `webpack-get-code-on-done` was removed from Suicrux.
